### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by pinbraerts** [pinbraerts/rekson#8]
Folders
1. input test data with objects in other programming language formats
2. output test data with resulting json
3. test that output is not changed after processing as well

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added a new test function 'other_language_formats' in the tests module of src/main.rs. This test processes input data with objects in Python and JavaScript formats, converts them to JSON, and verifies that the output remains unchanged after reprocessing.

You can review changes in this commit: https://github.com/lkilu6456546/pinbraerts-rekson-8/commit/16f6ecc318b52ef92caa17f2592f78124c41e433.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
